FROM n8nio/n8n:latest

ENV NODE_ENV=production
ENV GENERIC_TIMEZONE=America/La_Paz
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=admin123
ENV N8N_ENCRYPTION_KEY=clave_super_segura_cambia_esto
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678

EXPOSE 5678
CMD ["n8n", "start"]
